//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplementoPArcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancione
    {
        public int idcancion { get; set; }
        public Nullable<int> iddisco { get; set; }
        public Nullable<int> numero { get; set; }
        public string tiempo { get; set; }
        public string cancion { get; set; }
    
        public virtual disco disco { get; set; }
    }
}
