//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplementoPArcial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class complementoEntities : DbContext
    {
        public complementoEntities()
            : base("name=complementoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artista> artistas { get; set; }
        public virtual DbSet<cancione> canciones { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<detallepedido> detallepedidoes { get; set; }
        public virtual DbSet<disco> discos { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<pedido> pedidoes { get; set; }
    }
}
