//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplementoPArcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallepedido
    {
        public int iddetalle { get; set; }
        public Nullable<int> idpedido { get; set; }
        public Nullable<int> iddisco { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> precioVenta { get; set; }
    
        public virtual disco disco { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
