//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplementoPArcial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disco()
        {
            this.canciones = new HashSet<cancione>();
            this.detallepedidoes = new HashSet<detallepedido>();
        }
    
        public int iddisco { get; set; }
        public Nullable<int> idcategoria { get; set; }
        public Nullable<int> idartista { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string formato { get; set; }
        public Nullable<int> numeroCanciones { get; set; }
        public Nullable<double> precio { get; set; }
        public string observaciones { get; set; }
        public string imagen { get; set; }
    
        public virtual artista artista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cancione> canciones { get; set; }
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallepedido> detallepedidoes { get; set; }
    }
}
